#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class EllysScrabble {
public:
	string getMin(string letters, int maxDistance) {
		string ans = "";
		char todo[71];
		for(int i = 0;i<71;i++) todo[i] = 'Z'+1;
		for(int i = 0;i<letters.length();i++){
            int min_idx = i, min_type =0;
            for(int j = i+1;j<=min((int)letters.length()-1, i+maxDistance);j++){
                int cur_min = min_type?todo[min_idx]:letters[min_idx];
                if(cur_min > letters[j])
                    min_idx = j;
            }
            for(int j = i+1;j<=i+maxDistance;j++){
                int cur_min = min_type?todo[min_idx]:letters[min_idx];
                if(cur_min >= todo[j])
                    min_type = 1, min_idx = j;
            }
            if(letters[i] == 'Z'+1){
                letters[i] = min_type?todo[min_idx]:letters[min_idx];
                if(todo[i] != 'Z'+1){
                    letters[i] = todo[i];
                    todo[i] = 'Z'+1;
                }else if(min_type == 0)
                    letters[min_idx] = 'Z'+1;
                else
                    todo[min_idx] = 'Z'+1;
            }else{
                if(todo[i] != 'Z'+1){
                    todo[i+maxDistance] = letters[i];
                    letters[i] = todo[i];
                    todo[i] = 'Z'+1;
                }else if((min_type?todo[min_idx]:letters[min_idx]) < letters[i])
                {
                    if(min_type == 0){
                        todo[i+maxDistance] = letters[i];
                        letters[i] = min_type?todo[min_idx]:letters[min_idx];
                        letters[min_idx] = 'Z'+1;
                    }else{
                        todo[i+maxDistance] = letters[i];
                        letters[i] = min_type?todo[min_idx]:letters[min_idx];
                        todo[min_idx] = 'Z'+1;
                    }
                }
            }
//            cout<<letters<<endl;
//            for(int j=0;j<letters.size()+maxDistance;j++)
//                cout<<todo[j];
//            cout<<endl<<endl;
		}
		return letters;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, string p0, int p1, bool hasAnswer, string p2) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"" << "," << p1;
	cout << "]" << endl;
	EllysScrabble *obj;
	string answer;
	obj = new EllysScrabble();
	clock_t startTime = clock();
	answer = obj->getMin(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p2 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	string p0;
	int p1;
	string p2;

	{
	// ----- test 0 -----
	p0 = "TOPCODER";
	p1 = 3;
	p2 = "CODTEPOR";
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	p0 = "ESPRIT";
	p1 = 3;
	p2 = "EIPRST";
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	p0 = "BAZINGA";
	p1 = 8;
	p2 = "AABGINZ";
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	p0 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	p1 = 9;
	p2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	p0 = "GOODLUCKANDHAVEFUN";
	p1 = 7;
	p2 = "CADDGAHEOOFLUKNNUV";
	all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 5 -----
	p0 = "AAAWDIUAOIWDESBEAIWODJAWDBPOAWDUISAWDOOPAWD";
	p1 = 6;
	p2 = "AAAADDEIBWAEUIODWADSBIAJWODIAWDOPOAWDUOSPWW";
	all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 6 -----
	p0 = "ABRACADABRA";
	p1 = 2;
	p2 = "AABARACBDAR";
	all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
